# Site Info
title: No Excuses CCIE
tagline: 'My professional journey towards CCIE Route & Switch'
description: 'A personal blog and wiki outlining my path in obtaining my Cisco CCIE R&S.'
baseurl: ''
url: http://bsrandall.github.io
logo: '/public/logo.png'
blogurl: '/blog/'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Brian Scott Randall
  description: A dedicated network professional, working hard every day for my wife and child.
#  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
#  contact:
#    linkedin:  https://www.linkedin.com/in/lizhihao
#    github:    https://github.com/codinfox
    # facebook:  <hide>
#    twitter:   https://twitter.com/Li_Zhihao
#    weibo:     http://weibo.com/41173780
#    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://bsrandall.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/CCIE.png
  caption: Get the Number

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

collections:
    general-routing:
        output: true
        permalink: /general-routing/:path
